package net.kalinovcic.kinetix.simulation.animation;

public enum AnimationState
{
	COLLISION_APPROACH,
	COLLISION_INITIAL_VELOCITIES,
	COLLISION_NT,
	COLLISION_FINAL_VELOCITIES,
	COLLISION_LEAVING,
	;

	public AnimationState next;
	
	static
	{
		COLLISION_APPROACH.next = COLLISION_INITIAL_VELOCITIES;
		COLLISION_INITIAL_VELOCITIES.next = COLLISION_NT;
		COLLISION_NT.next = COLLISION_FINAL_VELOCITIES;
		COLLISION_FINAL_VELOCITIES.next = COLLISION_LEAVING;
		COLLISION_LEAVING.next = COLLISION_APPROACH;
	}
}
